SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Test](
[Id] int  NOT NULL
) ON [PRIMARY];
ALTER TABLE dbo.[Test] ADD CONSTRAINT
[PK_Test] PRIMARY KEY CLUSTERED
(
    [Id] 
) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
GO